README.md

README: add PAT as a prerequisite

---

playbooks/run.yml

Make root_dir fact configurable by GITSTYRING_ROOT_DIR env variable

---

playbooks/run.yml

Fix typo (looup -> lookup) & add missing true

---

roles/gitcontrol/tasks/repo-present.yml

Set root dir when calling the github_api.py script

---

roles/gitcontrol/tasks/repo-present.yml

Allow the protection rules not to be set

---

roles/gitcontrol/files/github_api.py
roles/gitcontrol/tasks/main.yml
roles/gitcontrol/tasks/teams-present.yml

for someone who need this not only inside sysconf

Teams and people management

---

roles/gitcontrol/tasks/repo-present.yml

Repair the detection if protection_rules is not set or empty

---

README.md
roles/gitcontrol/files/github_api.py
roles/gitcontrol/tasks/repo-present.yml

Make repositoy topics manageable

---

playbooks/library/scan_organizations.py

Ignore all non-yaml files in the orgs directory

---

orgs/opentelekomcloud-infra/repositories/apimon.yml
orgs/opentelekomcloud-infra/repositories/docsportal.yml

- add docsportal project
- change default branch of apimon
- change default branch of base-jobs

Add new project

---

orgs/opentelekomcloud/repositories/ansible-collection-gitcontrol.yml

- add new project
- fix definition for last added project

Add ansible collection project

---

orgs/opentelekomcloud/repositories/obs-obsutil.yml
orgs/opentelekomcloud/repositories/otcdocstheme.yml

- Move templates to the root
- Minor config changes

Minor config fixes

---

orgs/opentelekomcloud/repositories/DockerMachineDriver.yml
orgs/opentelekomcloud/repositories/docker-machine-opentelekomcloud.yml
orgs/opentelekomcloud/repositories/gophertelekomcloud.yml
orgs/opentelekomcloud/repositories/kontainer-engine-driver-otc.yml
orgs/opentelekomcloud/repositories/terraform-provider-opentelekomcloud.yml
orgs/opentelekomcloud/repositories/ui-cluster-driver-otc.yml
orgs/opentelekomcloud/repositories/ui-driver-otc.yml

* Add `gophers` team in go-related tools
* Add `jsers` team in js-related tools

Minor repository access changes

---

orgs/opentelekomcloud-blueprints/people/members.yml
orgs/opentelekomcloud-blueprints/teams/members.yml
orgs/opentelekomcloud-infra/people/members.yml
orgs/opentelekomcloud-infra/teams/members.yml
orgs/opentelekomcloud/people/members.yml
orgs/opentelekomcloud/teams/members.yml

Add new member

---

orgs/opentelekomcloud-blueprints/people/members.yml
orgs/opentelekomcloud-docs/people/members.yml
orgs/opentelekomcloud-infra/people/members.yml
orgs/opentelekomcloud/people/members.yml
orgs/terraform-opentelekomcloud-modules/people/members.yml

- sort org members by name
- complete user names to be real names

Tune org members

---

orgs/opentelekomcloud-docs/repositories/docs_on_docs.yml
orgs/opentelekomcloud-docs/repositories/docsportal.yml
orgs/opentelekomcloud-infra/repositories/octbot.yaml

- add new projects
- move docsportal under new org

Add new projects

---

orgs/opentelekomcloud-infra/repositories/identity-deploy.yml

Add `opentelekomcloud-infra/identity-deploy` to the project list

Add `identity-deploy` project

---

.zuul.yaml

Depends-On: https://github.com/opentelekomcloud-infra/otc-zuul-jobs/pull/133

add new secret

---

orgs/opentelekomcloud-infra/repositories/cloudmon-plugin-smtp.yml

- add blueprints/docs repository
- add cloudmon-plugin-smtp project

add cloudmon-plugin-smtp project

---

orgs/opentelekomcloud/repositories/DockerMachineDriver.yml
orgs/opentelekomcloud/repositories/docker-machine-opentelekomcloud.yml
orgs/opentelekomcloud/repositories/gophertelekomcloud.yml
orgs/opentelekomcloud/repositories/kontainer-engine-driver-otc.yml
orgs/opentelekomcloud/repositories/oms.yml
orgs/opentelekomcloud/repositories/terraform-provider-opentelekomcloud.yml
orgs/opentelekomcloud/repositories/ui-cluster-driver-otc.yml
orgs/opentelekomcloud/repositories/ui-driver-otc.yml
orgs/opentelekomcloud/repositories/vault-plugin-secrets-openstack.yml

- Add gophers team
- Add jsers team

Add missing teams in go/js-related tools

---

orgs/opentelekomcloud-docs/repositories/doc-exports.yml
orgs/opentelekomcloud-docs/repositories/security.yml

- add doc-exports repo
- add security project

Add doc-exports and security projects

---

orgs/opentelekomcloud-infra/repositories/cloudmon-metrics.yml

add cloudmon-metrics repo

---

data/github/orgs/opentelekomcloud/data.yaml
data/github/orgs/opentelekomcloud/repositories/gophertelekomcloud.yml
data/github/orgs/opentelekomcloud/repositories/terraform-provider-opentelekomcloud.yml

instead of enforcing all projects to have 2 reviews duplicate BP template

duplicate BP template

---

data/github/orgs/opentelekomcloud/repositories/terraform-provider-opentelekomcloud.yml

No need this anymore for terraform provider

Decrease number of approvers for tf provider

---

data/github/orgs/opentelekomcloud-docs/repositories/doc-exports.yml

Now we move this part to gitea

archive doc-exports

---

data/github/orgs/opentelekomcloud/repositories/terraform-modules-opentelekomcloud.yml

branch_protections branch name

---

data/github/orgs/opentelekomcloud/repositories/terraform-opentelekomcloud-project-factory

Need to use specific naming https://developer.hashicorp.com/terraform/registry/modules/publish#requirements

Rename terraform-modules-opentelekomcloud to terraform-opentelekomcloud-project-factory

---

data/github/orgs/stackmon/repositories/globalmon.yml

Add stackmon/globalmon repository to Zuul.

Add globalmon repository

---

data/github/orgs/opentelekomcloud/data.yaml
data/github/orgs/opentelekomcloud/repositories/cloud-provider-opentelekomcloud.yml

New template needed for repos where we are basically using gh actions

Template for basic GHactions wf

---

data/github/orgs/opentelekomcloud/repositories/python-otcextensions.yml

Change default branch python-otcextensions.yml

---

data/github/orgs/opentelekomcloud-infra/repositories/docs-next-charts.yml

that should fix issues with auto-pr creation

add otcbot to docs next charts repo

---

data/github/orgs/opentelekomcloud/data.yaml

Changed required approvals for gopheretelekomcloud to 2

zuul_2r approvals number

---

data/github/orgs/opentelekomcloud/repositories/gophertelekomcloud.yml

Update gophertelekomcloud.yml template
